### ISSUE TITLE
Lær spillet

### ISSUE THREAD

**Issue by Erlend-H-Dahl** [inf112-v20/BashBoys_Inc#5]
https://github.com/sivhollup/inf112/blob/master/v20/07-task-detailing/PITCHME.md

Runde:

Annonsere Powerdown
Dele ut kort
Programmere robot
Programmet godkjennes (om bare en spiller ikke er klar, start timer på 30sek)
Fase 1-2-3-4-5
Opprydding
Alle kort samles inn
Faser:

Snu programkort
Utfør bevegelse
Prioritert rekkefølge
Ekspressbånd 1 steg
Alle bånd 1 steg
Tannhjul roterer
Andre elementer og brettet aktiveres
Lasere aktiveres og skade deles ut
Flytte backup
Registrere flagg
Roboter har lasere med en retning

Vegger er ikke en hel rute, men ligger på kanten av en eller flere ruter.

Vegger stopper roboter
Vegger stopper også roboter som flyttes på grunn av dytting

**Comment by mathiash98** [comment]
https://github.com/sivhollup/inf112/blob/master/v20/07-task-detailing/PITCHME.md

Runde:
1. Annonsere Powerdown
2. Dele ut kort
3. Programmere robot
4. Programmet godkjennes (om bare en spiller ikke er klar, start timer på 30sek)
5. Fase 1-2-3-4-5
6. Opprydding
7.  Alle kort samles inn


Faser:
- Snu programkort
- Utfør bevegelse
  - Prioritert rekkefølge
- Ekspressbånd 1 steg
- Alle bånd 1 steg
- Tannhjul roterer
- Andre elementer og brettet aktiveres
- Lasere aktiveres og skade deles ut
- Flytte backup
- Registrere flagg

Roboter har lasere med en retning

Vegger er ikke en hel rute, men ligger på kanten av en eller flere ruter.
- Vegger stopper roboter
- Vegger stopper også roboter som flyttes på grunn av dytting
